version: "3.8"

services:
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nextjs-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # 👈 explicitly added this
      args:
        NEXT_PUBLIC_BACKEND_URL: http://flask-backend:5000
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://flask-backend:5000
    depends_on:
      - flask-backend
