name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: docker-compose build

      - name: Run backend tests with Pytest
        run: docker-compose run --rm flask-backend pytest

      - name: Start frontend and backend
        run: docker-compose up -d

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to be ready..."
          until curl -s http://localhost:3000 > /dev/null; do
            sleep 2
          done
          echo "Frontend is up!"

      - name: Run frontend tests with Playwright
        run: docker-compose exec -T nextjs-frontend npx playwright test

      - name: Stop and clean up
        if: always()
        run: docker-compose down --volumes --remove-orphans
